# Generated by Django 5.2.15 on 2026-09-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('we_learn_greek', '0007_user_date_joined_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
