# Generated by Django 5.2.15 on 2026-09-23 10:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('we_learn_greek', '0008_remove_user_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
    ]
