# Generated by Django 5.2.17 on 2026-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugator', '0003_alter_verb_infinitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='future_continuous_first_plural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='future_continuous_first_singular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='future_continuous_second_plural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='future_continuous_second_singular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='future_continuous_third_plural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='future_continuous_third_singular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
