# Generated by Django 5.2.17 on 2026-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greek_to_greek', '0002_alter_greektogreek_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='greektogreek',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greektogreek',
            name='pos',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='greektogreek',
            name='tier',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='greektogreek',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='greektogreek',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='greektogreek',
            constraint=models.UniqueConstraint(fields=('tier', 'content_id'), name='greektogreek_tier_content_id_unique'),
        ),
    ]
