# Generated by Django 5.2.15 on 2026-07-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transparrent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparentword',
            options={'ordering': ['language', 'greek_word']},
        ),
    ]
