# Generated by Django 5.2.17 on 2026-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparrent', '0002_alter_transparentword_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparentword',
            name='content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transparentword',
            name='tier',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddConstraint(
            model_name='transparentword',
            constraint=models.UniqueConstraint(fields=('language', 'content_id'), name='transparentword_language_content_id_unique'),
        ),
    ]
